### ISSUE TITLE
Built Android app

### ISSUE THREAD

**Issue by AKprisonER** [archos-sa/aos-Video#1]
Does this need compulsory Repo tool for building this app ?
HOw normal users can build this app ?
Repo tool size itself will eat our Hard disk

Any other solution for including the lib/dependencies to make a successful build ?
Windows and Android studio.

**Comment by courville** [comment]
Sorry for the late reply: repo is the easiest way to retrieve all the source for building the application (requiring many repositories). Repo in itself will not use much disk space.
